@startuml
title Full Architecture Diagram

' Define the major components/modules of the system

rectangle "Phases" {
    rectangle "Edit" {
    [Preload]
    [Postload]
    }
    rectangle "Gameplay" {
    [Startup]
    [AssignReinforcements]
    [IssueOrder]
    [OrderExecution]
    }
}

rectangle "Context" {
    [CommandLine]
    [CommandLine]-->[Phases]:User Commands

    [Edit]-->[Map]:Load Map
    [Startup]-->[Map]:Load Map
    [Postload]-->[Map]:Edit Map
    [Postload]-->[Map]:Save Map
    [Edit]-->[Map]:Show Map
    [Gameplay]-->[Map]:Show Map
    [Phases]-->[Map]:Validate Map

    [Phases]-->[Players]:Edit Players
    [Phases]-->[Players]:Assign Countries
    [Phases]-->[Players]:Queue Orders
    [Phases]-->[Players]:Execute Orders

    rectangle "Map" {
        [Continents]
        [Countries]
    }

    rectangle "Players" {
        [Orders]
    }
}

package "External Interactions" {
    (User Input) --> [CommandLine]
}

' External interactions
rectangle "Main" {
    [Main] --> [Context]
}
@enduml