# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow builds a Java project with Maven
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow will build a Java project with Maven, install dependencies, and run Checkstyle on your Java files

name: Java CI with Maven and Checkstyle

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 19
      uses: actions/setup-java@v4
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven

    - name: Install Maven dependencies
      run: mvn install -DskipTests=true

    - name: Compile Java files
      run: mvn compile

    - name: List Java files in src/main/java (for debugging)
      run: find src/main/java -name "*.java"

    - name: Run Maven build with Checkstyle
      run: |
        curl -sSL https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.45/checkstyle-8.45-all.jar -o checkstyle.jar
        java -jar checkstyle.jar -c checkstyle.xml $(find src/main/java src/test/java -name "*.java")

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run Unit Tests
      run: mvn test
